# Generated by Django 3.2.1 on 2021-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210523_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
