# Generated by Django 3.2.1 on 2021-06-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210607_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ('-id',), 'verbose_name': 'Composition', 'verbose_name_plural': 'Compositions'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainapp.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainapp.phonenumber', verbose_name='Phone'),
        ),
    ]
